# Generated by Django 5.2.4 on 2025-08-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
